import { Speelpot, Winkel, WinkelKaart } from '../types';

export const winkel: Winkel = {
  naam: 'Paper-Shop Beerse',
  adres: 'Markt 12, 2340 Beerse',
  logo: '🗞️',
  slug: 'paper-shop-beerse',
  kleur: 'primary',
};

export const winkelKaarten: WinkelKaart[] = [
  {
    slug: 'paper-shop-beerse',
    naam: 'Paper-Shop Beerse',
    stad: 'Beerse',
    adres: 'Markt 12, 2340 Beerse',
    emoji: '🗞️',
    aantalActievePotten: 2,
    totaalDeelnemers: 1390,
    volgendeTrekking: 'Vrijdag 9 mei',
    spel: 'EuroMillions',
    jackpot: '€ 87.000.000',
    nieuw: false,
  },
  {
    slug: 'krantenwinkel-gent-centrum',
    naam: 'Krantenwinkel Gent Centrum',
    stad: 'Gent',
    adres: 'Veldstraat 24, 9000 Gent',
    emoji: '📰',
    aantalActievePotten: 1,
    totaalDeelnemers: 312,
    volgendeTrekking: 'Zaterdag 10 mei',
    spel: 'Lotto',
    jackpot: '€ 3.200.000',
    nieuw: false,
  },
  {
    slug: 'lektuurshop-antwerpen',
    naam: 'Lektuurshop Antwerpen',
    stad: 'Antwerpen',
    adres: 'Meir 45, 2000 Antwerpen',
    emoji: '🏪',
    aantalActievePotten: 3,
    totaalDeelnemers: 847,
    volgendeTrekking: 'Vrijdag 9 mei',
    spel: 'Beide',
    jackpot: '€ 87.000.000',
    nieuw: true,
  },
  {
    slug: 'perswinkel-brussel',
    naam: 'Perswinkel Brussel-Noord',
    stad: 'Brussel',
    adres: 'Rue Neuve 78, 1000 Brussel',
    emoji: '📖',
    aantalActievePotten: 1,
    totaalDeelnemers: 203,
    volgendeTrekking: 'Vrijdag 9 mei',
    spel: 'EuroMillions',
    jackpot: '€ 87.000.000',
    nieuw: false,
  },
  {
    slug: 'tabak-press-brugge',
    naam: 'Tabak & Press Brugge',
    stad: 'Brugge',
    adres: 'Markt 3, 8000 Brugge',
    emoji: '🎫',
    aantalActievePotten: 2,
    totaalDeelnemers: 541,
    volgendeTrekking: 'Zaterdag 10 mei',
    spel: 'Lotto',
    jackpot: '€ 3.200.000',
    nieuw: true,
  },
  {
    slug: 'dagbladhandel-leuven',
    naam: 'Dagbladhandel Leuven',
    stad: 'Leuven',
    adres: 'Bondgenotenlaan 11, 3000 Leuven',
    emoji: '📚',
    aantalActievePotten: 1,
    totaalDeelnemers: 178,
    volgendeTrekking: 'Vrijdag 9 mei',
    spel: 'EuroMillions',
    jackpot: '€ 87.000.000',
    nieuw: false,
  },
  {
    slug: 'noballsnoglory-oostakker',
    naam: 'No Balls No Glory',
    stad: 'Oostakker',
    adres: 'Antwerpsesteenweg 592, 9041 Oostakker',
    emoji: '⚽',
    aantalActievePotten: 2,
    totaalDeelnemers: 89,
    volgendeTrekking: 'Vrijdag 9 mei',
    spel: 'EuroMillions',
    jackpot: '€ 87.000.000',
    nieuw: true,
  },
  {
    slug: 'presse-liege',
    naam: 'Presse Liège Centre',
    stad: 'Luik',
    adres: 'Rue de la Cathédrale 14, 4000 Liège',
    emoji: '🗺️',
    aantalActievePotten: 1,
    totaalDeelnemers: 267,
    volgendeTrekking: 'Zaterdag 10 mei',
    spel: 'Beide',
    jackpot: '€ 3.200.000',
    nieuw: false,
  },
];

export const speelpotten: Speelpot[] = [
  {
    id: 'sp-001',
    naam: 'EuroMillions Vrijdag',
    spel: 'EuroMillions',
    jackpot: '€ 87.000.000',
    prijsPerDeelname: 8,
    trekking: 'Vrijdag 9 mei 2026 – 21:00',
    status: 'open',
    aangemaakt: '2026-05-05',
    deelnemers: [
      { id: 'd1', naam: 'Jan Peeters', gsm: '0478 12 34 56', aantalDeelnames: 2, betaald: true, datum: '2026-05-06', smsStatus: 'verstuurd' },
      { id: 'd2', naam: 'Marie Claes', gsm: '0492 65 43 21', aantalDeelnames: 1, betaald: true, datum: '2026-05-06', smsStatus: 'verstuurd' },
      { id: 'd3', naam: 'Luc Vermeersch', gsm: '0476 98 76 54', aantalDeelnames: 3, betaald: true, datum: '2026-05-07', smsStatus: 'verstuurd' },
      { id: 'd4', naam: 'Sofie Janssens', gsm: '0486 11 22 33', aantalDeelnames: 1, betaald: false, datum: '2026-05-07', smsStatus: 'wachten' },
      { id: 'd5', naam: 'Peter De Smedt', gsm: '0468 44 55 66', aantalDeelnames: 2, betaald: true, datum: '2026-05-08', smsStatus: 'verstuurd' },
      { id: 'd6', naam: 'An Wouters', gsm: '0499 77 88 99', aantalDeelnames: 1, betaald: true, datum: '2026-05-08', smsStatus: 'verstuurd' },
    ],
  },
  {
    id: 'sp-002',
    naam: 'Lotto Maandpot',
    spel: 'Lotto',
    jackpot: '€ 3.200.000',
    prijsPerDeelname: 5,
    trekking: 'Zaterdag 10 mei 2026 – 19:00',
    status: 'open',
    aangemaakt: '2026-05-01',
    deelnemers: [
      { id: 'd7', naam: 'Ria Bogaerts', gsm: '0477 22 33 44', aantalDeelnames: 1, betaald: true, datum: '2026-05-03', smsStatus: 'verstuurd' },
      { id: 'd8', naam: 'Marc Hermans', gsm: '0494 55 66 77', aantalDeelnames: 2, betaald: true, datum: '2026-05-04', smsStatus: 'verstuurd' },
      { id: 'd9', naam: 'Ingrid Stevens', gsm: '0473 88 99 00', aantalDeelnames: 1, betaald: true, datum: '2026-05-05', smsStatus: 'verstuurd' },
    ],
  },
  {
    id: 'sp-003',
    naam: 'EuroMillions Maart',
    spel: 'EuroMillions',
    jackpot: '€ 45.000.000',
    prijsPerDeelname: 8,
    trekking: 'Vrijdag 15 maart 2026',
    status: 'getrokken',
    winnendBedrag: 1240,
    aangemaakt: '2026-03-10',
    deelnemers: [
      { id: 'd10', naam: 'Jan Peeters', gsm: '0478 12 34 56', aantalDeelnames: 2, betaald: true, datum: '2026-03-12', smsStatus: 'verstuurd' },
      { id: 'd11', naam: 'Luc Vermeersch', gsm: '0476 98 76 54', aantalDeelnames: 1, betaald: true, datum: '2026-03-12', smsStatus: 'verstuurd' },
      { id: 'd12', naam: 'Marie Claes', gsm: '0492 65 43 21', aantalDeelnames: 3, betaald: true, datum: '2026-03-13', smsStatus: 'verstuurd' },
    ],
  },
];
